package org.example.myclass;

public class OverLength {
    void longMethod() {
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
        System.out.println("hoge");
    }
}
